/* eslint-disable import/no-unresolved */
/* eslint-disable no-undef */
/* eslint-disable global-require */
/* eslint-disable import/prefer-default-export */
const Icon = {
  fullName: require('./UserLog.svg').default,
  userCreate: require('./userCreate.svg').default,
  password: require('./lock.svg').default,
  Google: require('./Google1.svg').default,
  FaceIc: require('./Facebook1.svg').default,
  Notification: require('./Notification.svg').default,
  Setting: require('./Setting.svg').default,
  Faq: require('./Faq.svg').default,
  QuickCreate: require('./QuickCreate.svg').default,
  DropDown: require('./DropDown.svg').default,
  Recent: require('./Recent.svg').default,
  Sales: require('./quick-sales.svg').default,
  General: require('./quick-general.svg').default,
  Purchase: require('./quick-purchase.svg').default,
  Dashboard: require('./Dashboard.svg').default,
  Inventory: require('./Inventory.svg').default,
  SalesSide: require('./Sales.svg').default,
  DropSide: require('./DropDown.svg').default,
  Documents: require('./Documents.svg').default,
  PurchaseSide: require('./Purchase.svg').default,
  Reports: require('./Reports.svg').default,
  Close: require('./Close.svg').default,
  DrpDwn: require('./DrpDwn.svg').default,
  ListView: require('./ListView.svg').default,
  Align: require('./Align.svg').default,
  BPlus: require('./BPlus.svg').default,
  Tips: require('./Tips.svg').default,
  Edit: require('./Edit.svg').default,
  Menu: require('./Menu.svg').default,
  Company: require('./Company.svg').default,
  Earth: require('./Earth.svg').default,
  Mail: require('./Mail.svg').default,
  Facebook: require('./Facebook.svg').default,
  Linkedin: require('./Linkedin.svg').default,
  Twitter: require('./Twitter.svg').default,
  Microsoft: require('./Microsoft.svg').default,
  Password: require('./Password.svg').default,
  Phone: require('./Phone.svg').default,
  SmallFaq: require('./SmallFaq.svg').default,
};
export default Icon;
