// ----- AUTH CONSTANTS
export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT_START = 'LOGOUT_START';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const CHECK_TOKEN = 'CHECK_TOKEN';
export const REGISTER_START = 'REGISTER_START';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';

// ----- ERROR CONSTANTS
export const SET_AUTH_ERR_MSG = 'SET_AUTH_ERR_MSG';
export const CLEAR_AUTH_ERR_MSG = 'CLEAR_AUTH_ERR_MSG';
export const SET_PRODUCT_ERR_MSG = 'SET_PRODUCT_ERR_MSG';
export const SET_CATEGORIES_ERR_MSG = 'SET_CATEGORIES_ERR_MSG';

// ----- LOADING CONSTANTS
export const SET_AUTH_LOADING = 'SET_AUTH_LOADING';
export const SET_GET_USER_LOADING = 'SET_GET_USER_LOADING';
export const SET_CREATE_USER_LOADING = 'SET_CREATE_USER_LOADING';
export const SET_GET_PRODUCTS_LOADING = 'SET_GET_PRODUCTS_LOADING';
export const SET_CREATE_PRODUCTS_LOADING = 'SET_CREATE_PRODUCTS_LOADING';
export const SET_GET_CATEGORIES_LOADING = 'SET_GET_CATEGORIES_LOADING';
export const SET_CREATE_CATEGORIES_LOADING = 'SET_CREATE_CATEGORIES_LOADING';
export const SET_GET_CUSTOMERS_LOADING = 'SET_GET_CUSTOMERS_LOADING';
export const SET_CREATE_CUSTOMERS_LOADING = 'SET_CREATE_CUSTOMERS_LOADING';
export const SET_GET_BILLS_LOADING = 'SET_GET_BILLS_LOADING';

// ----- PRODUCT CONSTANTS
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const CREATE_PRODUCT = 'CREATE_PRODUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';

// ----- PRODUCT LIST FAIL CONSTANTS
export const GET_PRODUCTS_FAIL = 'GET_PRODUCTS_FAIL';
export const CREATE_PRODUCT_FAIL = 'CREATE_PRODUCT_FAIL';
export const UPDATE_PRODUCT_FAIL = 'UPDATE_PRODUCT_FAIL';
export const DELETE_PRODUCT_FAIL = 'DELETE_PRODUCT_FAIL';

// ----- PRODUCT LIST SUCCESS CONSTANTS
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const CREATE_PRODUCT_SUCCESS = 'CREATE_PRODUCT_SUCCESS';
export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS';
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS';

// ----- CATEGORY CONSTANTS
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const CREATE_CATEGORY = 'CREATE_CATEGORY';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';

// ----- CATEGORY LIST FAIL CONSTANTS
export const GET_CATEGORIES_FAIL = 'GET_CATEGORIES_FAIL';
export const CREATE_CATEGORY_FAIL = 'CREATE_CATEGORY_FAIL';
export const DELETE_CATEGORY_FAIL = 'DELETE_CATEGORY_FAIL';
export const UPDATE_CATEGORY_FAIL = 'UPDATE_CATEGORY_FAIL';

// ----- CATEGORY LIST SUCCESS CONSTANTS
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const CREATE_CATEGORY_SUCCESS = 'CREATE_CATEGORY_SUCCESS';
export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS';
export const UPDATE_CATEGORY_SUCCESS = 'UPDATE_CATEGORY_SUCCESS';

// ----- CUSTOMER CONSTANTS
export const GET_CUSTOMERS = 'GET_CUSTOMERS';
export const CREATE_CUSTOMERS = 'CREATE_CUSTOMERS';
export const UPDATE_CUSTOMERS = 'UPDATE_CUSTOMERS';
export const DELETE_CUSTOMERS = 'DELETE_CUSTOMERS';

// ----- TOGGLE MENU CONSTANTS
export const TOGGLE_OPEN_MENU = 'TOGGLE_OPEN_MENU';
export const TOGGLE_CLOSE_MENU = 'TOGGLE_CLOSE_MENU';
