// ----- AUTH CONSTANTS
export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT_START = 'LOGOUT_START';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const CHECK_TOKEN = 'CHECK_TOKEN';
export const REGISTER_START = 'REGISTER_START';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';

// ----- ERROR CONSTANTS
export const SET_AUTH_ERR_MSG = 'SET_AUTH_ERR_MSG';
export const CLEAR_AUTH_ERR_MSG = 'CLEAR_AUTH_ERR_MSG';
export const SET_PRODUCT_ERR_MSG = 'SET_PRODUCT_ERR_MSG';
export const SET_CATEGORIES_ERR_MSG = 'SET_CATEGORIES_ERR_MSG';

// ----- LOADING CONSTANTS
export const SET_AUTH_LOADING = 'SET_AUTH_LOADING';
export const SET_GET_USER_LOADING = 'SET_GET_USER_LOADING';
export const SET_CREATE_USER_LOADING = 'SET_CREATE_USER_LOADING';
export const SET_GET_PRODUCTS_LOADING = 'SET_GET_PRODUCTS_LOADING';
export const SET_CREATE_PRODUCTS_LOADING = 'SET_CREATE_PRODUCTS_LOADING';
export const SET_GET_CATEGORIES_LOADING = 'SET_GET_CATEGORIES_LOADING';
export const SET_CREATE_CATEGORIES_LOADING = 'SET_CREATE_CATEGORIES_LOADING';
export const SET_GET_CUSTOMERS_LOADING = 'SET_GET_CUSTOMERS_LOADING';
export const SET_CREATE_CUSTOMERS_LOADING = 'SET_CREATE_CUSTOMERS_LOADING';
export const SET_GET_BILLS_LOADING = 'SET_GET_BILLS_LOADING';
